[project]
authors = ["aegroto <aegroto@protonmail.com>"]
channels = ["conda-forge"]
description = "ICIP 2024 - Implicit Image Compression 101"
name = "icip-2024-inr-images-tutorial"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
fit = "python -m bin.fit"

[dependencies]
python = "3.12"
pytorch = "2.4.0"
scikit-image = ">=0.24.0,<0.25"
pillow = ">=10.4.0,<11"
torchvision = ">=0.19.1,<0.20"
